### ISSUE TITLE
PG viscosity vs temperature

### ISSUE THREAD

**Issue by marcocaggioni** [ManonMarchand/three_component_model#1]
Propylene Glycol viscosity as a function of temperature.

![image](https://user-images.githubusercontent.com/5448255/162071073-d9c68800-3640-4b6f-9156-34242af148f5.png)

Stress | Shear rate | Viscosity | Step time | Temperature | Normal stress
-- | -- | -- | -- | -- | --
10.2619 | 100.001 | 0.102618 | 10.0320 | 10.09 | -50.1984
10.2098 | 100.003 | 0.102095 | 20.0440 | 10.27 | -50.1787
10.1436 | 99.9983 | 0.101438 | 30.0480 | 10.45 | -46.0679
10.0466 | 100.000 | 0.100466 | 40.0400 | 10.63 | -52.9031
9.96069 | 99.9980 | 0.0996089 | 50.0400 | 10.81 | -49.4182
9.87081 | 99.9978 | 0.0987103 | 60.0360 | 10.97 | -53.7363
9.74983 | 100.005 | 0.0974938 | 70.0360 | 11.16 | -52.9838
9.67487 | 100.002 | 0.0967470 | 80.0360 | 11.30 | -52.3297
9.56153 | 100.000 | 0.0956153 | 90.0360 | 11.48 | -48.1138
9.45858 | 99.9980 | 0.0945876 | 100.036 | 11.66 | -53.3976
9.35813 | 100.003 | 0.0935783 | 110.032 | 11.84 | -50.1454
9.25804 | 100.001 | 0.0925796 | 120.032 | 11.97 | -49.5561
9.15181 | 100.003 | 0.0915157 | 130.028 | 12.14 | -47.9007
9.05685 | 99.9960 | 0.0905721 | 140.036 | 12.32 | -49.6996
8.95748 | 100.000 | 0.0895748 | 150.036 | 12.49 | -50.5990
8.85667 | 99.9992 | 0.0885675 | 160.032 | 12.64 | -55.2721
8.75289 | 100.001 | 0.0875281 | 170.032 | 12.83 | -47.9757
8.65542 | 99.9986 | 0.0865554 | 180.028 | 13.00 | -56.4427
8.56679 | 99.9975 | 0.0856701 | 190.048 | 13.16 | -49.8141
8.47411 | 99.9972 | 0.0847434 | 200.048 | 13.31 | -52.5819
8.36781 | 100.003 | 0.0836759 | 210.028 | 13.48 | -49.3949
8.26515 | 99.9998 | 0.0826517 | 220.040 | 13.68 | -49.3724
8.19258 | 99.9995 | 0.0819262 | 230.040 | 13.83 | -53.1000
8.10610 | 100.002 | 0.0810591 | 240.040 | 13.97 | -50.8575
8.01096 | 100.003 | 0.0801069 | 250.036 | 14.18 | -52.4290
7.91529 | 99.9995 | 0.0791533 | 260.044 | 14.33 | -50.2030
7.81652 | 99.9986 | 0.0781663 | 270.044 | 14.50 | -49.2201
7.74311 | 99.9992 | 0.0774317 | 280.040 | 14.64 | -54.5639
7.65358 | 99.9972 | 0.0765380 | 290.040 | 14.83 | -56.7445
7.57779 | 100.000 | 0.0757778 | 300.040 | 14.98 | -51.9846
7.49709 | 99.9992 | 0.0749715 | 310.040 | 15.15 | -51.1040
7.39688 | 100.002 | 0.0739673 | 320.048 | 15.33 | -54.8147
7.33350 | 99.9963 | 0.0733377 | 330.040 | 15.48 | -57.0556
7.25096 | 100.001 | 0.0725085 | 340.032 | 15.65 | -55.1684
7.16263 | 100.003 | 0.0716238 | 350.032 | 15.84 | -56.4667
7.08427 | 100.002 | 0.0708414 | 360.032 | 15.99 | -55.5042
7.00572 | 99.9963 | 0.0700598 | 370.028 | 16.15 | -55.1292
6.92616 | 99.9978 | 0.0692632 | 380.028 | 16.32 | -57.4296
6.85735 | 100.003 | 0.0685715 | 390.044 | 16.49 | -55.2299
6.79277 | 100.008 | 0.0679221 | 400.044 | 16.65 | -56.4473
6.70426 | 100.001 | 0.0670420 | 410.036 | 16.83 | -54.6045
6.63795 | 100.000 | 0.0663793 | 420.036 | 16.98 | -52.7812
6.56067 | 100.001 | 0.0656063 | 430.032 | 17.16 | -55.9231
6.49334 | 100.002 | 0.0649323 | 440.032 | 17.32 | -57.5006
6.41528 | 100.001 | 0.0641522 | 450.032 | 17.49 | -57.5624
6.35076 | 99.9963 | 0.0635099 | 460.036 | 17.66 | -58.2526
6.28756 | 100.000 | 0.0628755 | 470.032 | 17.82 | -56.7236
6.21223 | 100.000 | 0.0621221 | 480.024 | 18.00 | -48.9070
6.14527 | 99.9998 | 0.0614529 | 490.028 | 18.16 | -53.0183
6.08117 | 100.003 | 0.0608098 | 500.024 | 18.33 | -53.3928
6.02573 | 100.004 | 0.0602550 | 510.040 | 18.48 | -57.1691
5.95804 | 99.9983 | 0.0595814 | 520.036 | 18.65 | -50.9831
5.90200 | 99.9978 | 0.0590213 | 530.024 | 18.83 | -57.6302
5.83574 | 100.002 | 0.0583562 | 540.044 | 18.98 | -58.8692
5.77754 | 100.000 | 0.0577753 | 550.024 | 19.14 | -55.8521
5.71262 | 99.9980 | 0.0571273 | 560.036 | 19.32 | -54.6398
5.65730 | 99.9929 | 0.0565770 | 570.024 | 19.50 | -54.6829
5.60105 | 99.9978 | 0.0560118 | 580.036 | 19.65 | -54.7035
5.53154 | 100.003 | 0.0553136 | 590.040 | 19.83 | -51.6251
5.47681 | 100.001 | 0.0547674 | 600.032 | 20.01 | -49.7641
5.41221 | 99.9980 | 0.0541232 | 610.032 | 20.17 | -50.4556
5.36339 | 99.9986 | 0.0536346 | 620.032 | 20.33 | -54.5246
5.31679 | 99.9998 | 0.0531680 | 630.036 | 20.49 | -57.1689
5.25136 | 100.002 | 0.0525127 | 640.028 | 20.66 | -54.6957
5.20180 | 100.005 | 0.0520152 | 650.024 | 20.83 | -50.8645
5.15194 | 99.9983 | 0.0515203 | 660.028 | 20.99 | -56.0615
5.09240 | 99.9992 | 0.0509244 | 670.032 | 21.18 | -53.9239
5.04842 | 99.9989 | 0.0504848 | 680.036 | 21.33 | -48.9177
4.99706 | 99.9992 | 0.0499710 | 690.024 | 21.50 | -50.8699
4.94339 | 100.003 | 0.0494322 | 700.036 | 21.65 | -50.5979
4.89454 | 100.001 | 0.0489448 | 710.032 | 21.84 | -50.3308
4.84248 | 99.9998 | 0.0484250 | 720.032 | 22.01 | -51.6950
4.79616 | 99.9980 | 0.0479625 | 730.028 | 22.17 | -52.9744
4.74721 | 100.003 | 0.0474705 | 740.032 | 22.33 | -51.1549
4.69990 | 100.003 | 0.0469978 | 750.028 | 22.48 | -52.0790
4.65741 | 100.002 | 0.0465733 | 760.024 | 22.61 | -51.8514
4.61231 | 99.9920 | 0.0461268 | 770.020 | 22.82 | -54.1350
4.56787 | 99.9986 | 0.0456793 | 780.032 | 22.99 | -49.1486
4.50658 | 99.9983 | 0.0450665 | 790.032 | 23.16 | -55.4809
4.47006 | 99.9992 | 0.0447010 | 800.032 | 23.31 | -55.8427
4.42325 | 99.9978 | 0.0442335 | 810.028 | 23.50 | -55.2791
4.38129 | 99.9998 | 0.0438130 | 820.028 | 23.67 | -51.2326
4.34076 | 99.9963 | 0.0434092 | 830.024 | 23.83 | -54.7194
4.27913 | 100.003 | 0.0427900 | 840.028 | 23.98 | -54.1732
4.24103 | 99.9952 | 0.0424124 | 850.032 | 24.16 | -54.4725
4.20217 | 100.000 | 0.0420217 | 860.032 | 24.33 | -56.1093
4.15769 | 100.003 | 0.0415758 | 870.024 | 24.49 | -50.7276
4.12487 | 99.9926 | 0.0412517 | 880.028 | 24.65 | -50.8120
4.08743 | 99.9989 | 0.0408748 | 890.024 | 24.83 | -55.3380
4.03902 | 100.000 | 0.0403902 | 900.024 | 24.99 | -52.8293
4.00272 | 99.9960 | 0.0400288 | 910.020 | 25.15 | -53.1667
3.96709 | 99.9975 | 0.0396719 | 920.020 | 25.29 | -57.0421
3.92986 | 99.9998 | 0.0392987 | 930.036 | 25.48 | -52.6251
3.89507 | 99.9980 | 0.0389515 | 940.032 | 25.67 | -52.0427
3.84373 | 100.000 | 0.0384372 | 950.032 | 25.83 | -56.1707
3.81478 | 99.9963 | 0.0381492 | 960.028 | 26.01 | -58.4368
3.78040 | 100.001 | 0.0378038 | 970.032 | 26.16 | -59.0678
3.74063 | 100.001 | 0.0374059 | 980.024 | 26.34 | -55.6711
3.70103 | 100.003 | 0.0370093 | 990.020 | 26.50 | -53.7902
3.66645 | 100.000 | 0.0366643 | 1000.02 | 26.66 | -53.5205
3.63438 | 99.9998 | 0.0363439 | 1010.02 | 26.84 | -53.8989
3.59934 | 100.002 | 0.0359925 | 1020.03 | 27.00 | -54.1572
3.57301 | 100.002 | 0.0357292 | 1030.03 | 27.15 | -52.9617
3.53566 | 99.9992 | 0.0353569 | 1040.03 | 27.30 | -53.3804
3.51040 | 99.9986 | 0.0351045 | 1050.02 | 27.49 | -57.7408
3.46718 | 100.001 | 0.0346713 | 1060.02 | 27.67 | -51.1876
3.44724 | 99.9995 | 0.0344726 | 1070.03 | 27.82 | -54.3915
3.40593 | 99.9986 | 0.0340598 | 1080.04 | 27.98 | -55.2551
3.37723 | 100.003 | 0.0337711 | 1090.03 | 28.16 | -59.8049
3.34051 | 100.002 | 0.0334044 | 1100.03 | 28.34 | -57.3101
3.31605 | 99.9986 | 0.0331609 | 1110.03 | 28.50 | -59.7885
3.28082 | 99.9975 | 0.0328090 | 1120.02 | 28.68 | -55.4709
3.25128 | 100.001 | 0.0325125 | 1130.03 | 28.83 | -57.5897
3.22889 | 100.004 | 0.0322876 | 1140.02 | 28.96 | -51.6996
3.19485 | 99.9980 | 0.0319492 | 1150.02 | 29.16 | -51.4295
3.17469 | 99.9992 | 0.0317472 | 1160.03 | 29.33 | -53.0255
3.13537 | 100.001 | 0.0313534 | 1170.02 | 29.51 | -52.6693
3.11084 | 100.003 | 0.0311076 | 1180.02 | 29.65 | -54.0076
3.08024 | 100.001 | 0.0308021 | 1190.02 | 29.82 | -57.1369
3.05952 | 99.9980 | 0.0305958 | 1200.02 | 29.97 | -54.3277
3.03243 | 99.9978 | 0.0303250 | 1210.03 | 30.14 | -53.4068
3.00014 | 100.000 | 0.0300013 | 1220.03 | 30.32 | -49.9702
2.97752 | 100.001 | 0.0297747 | 1230.02 | 30.49 | -52.7583
2.94513 | 100.000 | 0.0294512 | 1240.02 | 30.66 | -53.1356
2.92124 | 99.9978 | 0.0292130 | 1250.03 | 30.83 | -57.5409
2.89899 | 100.007 | 0.0289880 | 1260.03 | 30.99 | -52.4688
2.86817 | 100.007 | 0.0286796 | 1270.04 | 31.14 | -55.6151
2.84314 | 100.002 | 0.0284307 | 1280.05 | 31.34 | -53.6854
2.81827 | 100.003 | 0.0281818 | 1290.02 | 31.52 | -52.0989
2.79464 | 100.001 | 0.0279461 | 1300.02 | 31.66 | -55.9334
2.77958 | 99.9998 | 0.0277959 | 1310.02 | 31.83 | -53.7089
2.75914 | 99.9980 | 0.0275920 | 1320.02 | 31.98 | -56.2474
2.73359 | 100.006 | 0.0273342 | 1330.04 | 32.14 | -55.0288
2.70509 | 100.003 | 0.0270502 | 1340.03 | 32.36 | -57.5076
2.68187 | 100.001 | 0.0268185 | 1350.02 | 32.47 | -51.5379
2.66410 | 99.9943 | 0.0266425 | 1360.02 | 32.67 | -55.5600
2.63661 | 100.003 | 0.0263653 | 1370.02 | 32.82 | -56.2906
2.60998 | 100.001 | 0.0260995 | 1380.02 | 33.01 | -54.0070
2.59744 | 100.002 | 0.0259738 | 1390.02 | 33.16 | -56.9191
2.57354 | 99.9975 | 0.0257361 | 1400.02 | 33.32 | -53.3987
2.55970 | 99.9972 | 0.0255977 | 1410.02 | 33.47 | -56.5629
2.52550 | 100.000 | 0.0252549 | 1420.02 | 33.65 | -55.2258
2.50485 | 100.001 | 0.0250482 | 1430.01 | 33.82 | -55.8526
2.48386 | 99.9972 | 0.0248393 | 1440.03 | 34.01 | -53.6908
2.46908 | 99.9986 | 0.0246911 | 1450.02 | 34.15 | -52.4339
2.45466 | 99.9920 | 0.0245486 | 1460.02 | 34.31 | -50.8623
2.41745 | 100.002 | 0.0241740 | 1470.05 | 34.52 | -58.3242
2.40602 | 99.9975 | 0.0240608 | 1480.02 | 34.65 | -55.1798
2.38830 | 100.001 | 0.0238828 | 1490.02 | 34.83 | -52.4312
2.36519 | 99.9995 | 0.0236520 | 1500.02 | 35.00 | -51.0706
2.35363 | 99.9940 | 0.0235377 | 1510.01 | 35.13 | -54.1942
2.34157 | 99.9969 | 0.0234164 | 1520.02 | 35.33 | -57.0828
2.30729 | 100.001 | 0.0230727 | 1530.03 | 35.50 | -55.6996
2.29310 | 100.001 | 0.0229307 | 1540.02 | 35.65 | -57.6251
2.27112 | 99.9975 | 0.0227118 | 1550.02 | 35.84 | -52.9332
2.25307 | 100.000 | 0.0225307 | 1560.02 | 36.01 | -55.0269
2.24160 | 99.9980 | 0.0224165 | 1570.02 | 36.17 | -58.5268
2.21507 | 100.000 | 0.0221507 | 1580.02 | 36.30 | -56.5793
2.20581 | 99.9920 | 0.0220599 | 1590.02 | 36.47 | -57.8143
2.18514 | 100.001 | 0.0218511 | 1600.02 | 36.66 | -53.4107
2.16374 | 100.004 | 0.0216366 | 1610.03 | 36.87 | -57.1801
2.14286 | 100.003 | 0.0214280 | 1620.01 | 36.99 | -57.1769
2.12801 | 100.004 | 0.0212793 | 1630.02 | 37.13 | -55.8583
2.11064 | 100.001 | 0.0211063 | 1640.02 | 37.33 | -59.0019
2.09327 | 100.001 | 0.0209325 | 1650.02 | 37.53 | -54.8294
2.08324 | 100.003 | 0.0208319 | 1660.02 | 37.64 | -57.9708
2.06415 | 100.001 | 0.0206412 | 1670.03 | 37.81 | -55.7279
2.04720 | 100.001 | 0.0204718 | 1680.03 | 38.00 | -55.1169
2.02608 | 100.002 | 0.0202603 | 1690.02 | 38.19 | -55.7224
2.02563 | 100.003 | 0.0202556 | 1700.02 | 38.30 | -56.9800
2.00089 | 100.003 | 0.0200084 | 1710.01 | 38.49 | -59.0934
1.98314 | 100.000 | 0.0198314 | 1720.01 | 38.68 | -56.9533
1.95945 | 100.001 | 0.0195942 | 1730.01 | 38.85 | -54.6452
1.94953 | 99.9998 | 0.0194954 | 1740.01 | 39.00 | -52.4649
1.93536 | 99.9963 | 0.0193543 | 1750.02 | 39.13 | -56.1946
1.92122 | 100.000 | 0.0192121 | 1760.02 | 39.30 | -53.6518
1.90858 | 100.000 | 0.0190858 | 1770.02 | 39.48 | -53.3389
1.89035 | 99.9978 | 0.0189039 | 1780.02 | 39.68 | -55.4537
1.87925 | 99.9992 | 0.0187927 | 1790.02 | 39.86 | -55.0942
1.85795 | 100.001 | 0.0185794 | 1800.02 | 39.97 | -52.9316
1.85159 | 100.007 | 0.0185147 | 1810.02 | 40.13 | -57.6055
1.82944 | 100.003 | 0.0182937 | 1820.02 | 40.34 | -55.4147
1.82369 | 99.9989 | 0.0182372 | 1830.02 | 40.51 | -55.9816
1.81101 | 99.9969 | 0.0181107 | 1840.02 | 40.67 | -55.3293
1.79267 | 100.002 | 0.0179263 | 1850.02 | 40.81 | -54.0866
1.78832 | 100.005 | 0.0178824 | 1860.02 | 40.98 | -56.4760
1.76314 | 99.9983 | 0.0176317 | 1870.02 | 41.15 | -57.6715
1.75546 | 99.9969 | 0.0175551 | 1880.02 | 41.34 | -56.7002
1.73418 | 100.003 | 0.0173413 | 1890.01 | 41.53 | -55.1660
1.72376 | 100.003 | 0.0172371 | 1900.02 | 41.64 | -55.0598
1.71477 | 100.001 | 0.0171475 | 1910.01 | 41.80 | -59.7713
1.70377 | 100.007 | 0.0170366 | 1920.01 | 42.00 | -50.0612
1.68811 | 100.003 | 0.0168805 | 1930.00 | 42.18 | -56.6208
1.68101 | 100.001 | 0.0168100 | 1940.01 | 42.33 | -58.4374
1.67542 | 99.9978 | 0.0167546 | 1950.02 | 42.47 | -54.6005
1.65442 | 100.003 | 0.0165436 | 1960.01 | 42.66 | -50.7846
1.64962 | 100.003 | 0.0164956 | 1970.01 | 42.82 | -55.1373
1.62853 | 99.9995 | 0.0162853 | 1980.00 | 43.01 | -52.9298
1.62435 | 99.9975 | 0.0162439 | 1990.02 | 43.19 | -53.2184
1.60507 | 100.004 | 0.0160501 | 2000.02 | 43.30 | -53.5488
1.59723 | 100.001 | 0.0159720 | 2010.02 | 43.46 | -55.6831
1.59118 | 99.9989 | 0.0159119 | 2020.03 | 43.67 | -52.4740
1.57927 | 99.9963 | 0.0157933 | 2030.01 | 43.84 | -59.3431
1.58104 | 99.9943 | 0.0158113 | 2040.01 | 43.99 | -54.3274
1.54964 | 99.9992 | 0.0154965 | 2050.01 | 44.14 | -53.8857
1.54790 | 100.001 | 0.0154789 | 2060.01 | 44.32 | -56.1021
1.53300 | 99.9963 | 0.0153306 | 2070.02 | 44.49 | -57.0408
1.52499 | 99.9989 | 0.0152501 | 2080.02 | 44.68 | -55.6931
1.52030 | 99.9957 | 0.0152037 | 2090.00 | 44.83 | -61.0136
1.49794 | 100.001 | 0.0149794 | 2100.00 | 44.97 | -51.8253
1.49711 | 99.9952 | 0.0149718 | 2110.02 | 45.15 | -53.0538
1.47272 | 100.002 | 0.0147270 | 2120.02 | 45.36 | -51.1640
1.47190 | 99.9998 | 0.0147190 | 2130.01 | 45.50 | -54.8485
1.46444 | 99.9975 | 0.0146448 | 2140.03 | 45.63 | -55.1163
1.45982 | 99.9989 | 0.0145984 | 2150.01 | 45.84 | -52.5937
1.43593 | 100.001 | 0.0143592 | 2160.01 | 46.02 | -58.8356
1.43392 | 100.003 | 0.0143388 | 2170.01 | 46.13 | -52.8727
1.42081 | 99.9957 | 0.0142087 | 2180.01 | 46.32 | -53.6884
1.40686 | 99.9995 | 0.0140687 | 2190.00 | 46.51 | -52.4685
1.40448 | 99.9983 | 0.0140450 | 2200.00 | 46.68 | -54.5591
1.38712 | 99.9995 | 0.0138713 | 2210.02 | 46.84 | -53.8620
1.38837 | 99.9955 | 0.0138844 | 2220.02 | 46.98 | -53.3101
1.37087 | 100.003 | 0.0137083 | 2230.01 | 47.14 | -54.1830
1.36416 | 100.003 | 0.0136411 | 2240.01 | 47.33 | -55.1162
1.34557 | 100.002 | 0.0134554 | 2250.01 | 47.52 | -57.2702
1.34210 | 100.001 | 0.0134208 | 2260.00 | 47.66 | -56.2603
1.33434 | 99.9972 | 0.0133437 | 2270.00 | 47.79 | -57.8261
1.32620 | 100.001 | 0.0132618 | 2280.04 | 47.99 | -53.9435
1.31753 | 100.006 | 0.0131746 | 2290.02 | 48.19 | -52.0698
1.30360 | 99.9960 | 0.0130366 | 2300.01 | 48.35 | -54.8518
1.30389 | 100.002 | 0.0130386 | 2310.02 | 48.49 | -55.5123
1.28836 | 100.001 | 0.0128835 | 2320.02 | 48.63 | -54.7939
1.29063 | 99.9960 | 0.0129068 | 2330.01 | 48.83 | -56.2955
1.27263 | 100.003 | 0.0127259 | 2340.02 | 49.00 | -58.4904
1.26831 | 100.003 | 0.0126828 | 2350.01 | 49.15 | -54.4176
1.25194 | 100.000 | 0.0125194 | 2360.00 | 49.34 | -54.6236
1.25007 | 99.9989 | 0.0125008 | 2370.00 | 49.50 | -58.0527
1.24187 | 99.9963 | 0.0124191 | 2380.00 | 49.65 | -56.0978
1.23250 | 100.003 | 0.0123247 | 2390.02 | 49.82 | -56.0073
1.22644 | 100.004 | 0.0122639 | 2400.01 | 50.00 | -55.0972
1.21819 | 99.9986 | 0.0121821 | 2410.02 | 50.15 | -54.7122
1.21426 | 100.003 | 0.0121423 | 2420.02 | 50.35 | -52.2307
1.19650 | 100.001 | 0.0119649 | 2430.01 | 50.48 | -54.7176
1.19369 | 100.003 | 0.0119365 | 2440.01 | 50.66 | -52.7627
1.18214 | 100.001 | 0.0118213 | 2450.01 | 50.86 | -52.7545
1.17954 | 99.9998 | 0.0117954 | 2460.01 | 50.98 | -54.5725
1.17623 | 100.001 | 0.0117621 | 2470.01 | 51.13 | -55.4639
1.15871 | 100.003 | 0.0115868 | 2480.01 | 51.35 | -57.5522
1.16066 | 100.003 | 0.0116062 | 2490.02 | 51.50 | -54.3436
1.14688 | 100.001 | 0.0114687 | 2500.00 | 51.62 | -56.8907
1.14450 | 99.9980 | 0.0114452 | 2510.01 | 51.83 | -50.8670
1.13095 | 100.003 | 0.0113092 | 2520.01 | 52.02 | -54.2166
1.13383 | 99.9998 | 0.0113383 | 2530.00 | 52.13 | -55.1306
1.11434 | 100.001 | 0.0111432 | 2540.00 | 52.34 | -51.3291
1.11319 | 100.003 | 0.0111315 | 2550.03 | 52.48 | -54.4660
1.09920 | 99.9998 | 0.0109920 | 2560.02 | 52.66 | -53.8082
1.09523 | 99.9972 | 0.0109526 | 2570.01 | 52.85 | -51.5971
1.09664 | 100.000 | 0.0109663 | 2580.01 | 52.99 | -56.2430
1.08381 | 100.003 | 0.0108377 | 2590.00 | 53.12 | -55.9006
1.08623 | 100.003 | 0.0108619 | 2600.00 | 53.33 | -52.0989
1.07311 | 100.001 | 0.0107310 | 2610.01 | 53.53 | -57.1000
1.07599 | 99.9992 | 0.0107600 | 2620.00 | 53.66 | -53.2367
1.06183 | 100.002 | 0.0106180 | 2630.00 | 53.78 | -50.9848
1.05342 | 100.000 | 0.0105342 | 2640.00 | 54.02 | -55.3789
1.05368 | 99.9972 | 0.0105371 | 2650.00 | 54.17 | -55.0143
1.04744 | 99.9975 | 0.0104747 | 2660.01 | 54.29 | -53.0993
1.04997 | 99.9998 | 0.0104997 | 2670.02 | 54.54 | -56.1917
1.02901 | 99.9989 | 0.0102902 | 2680.01 | 54.64 | -53.6080
1.02737 | 100.003 | 0.0102734 | 2690.02 | 54.80 | -50.1831
1.01539 | 99.9957 | 0.0101543 | 2700.01 | 55.00 | -54.5335
1.01501 | 100.002 | 0.0101499 | 2710.01 | 55.17 | -51.3389
1.01227 | 99.9960 | 0.0101231 | 2720.00 | 55.31 | -56.6542
0.995944 | 99.9995 | 9.95949e-3 | 2730.01 | 55.51 | -54.3848
1.00287 | 99.9983 | 0.0100288 | 2740.02 | 55.66 | -56.8054
0.979000 | 99.9992 | 9.79008e-3 | 2750.00 | 55.82 | -55.8333
0.976195 | 99.9975 | 9.76219e-3 | 2760.00 | 56.00 | -53.9583
0.971862 | 99.9986 | 9.71875e-3 | 2770.00 | 56.13 | -53.5749
0.972948 | 99.9989 | 9.72959e-3 | 2780.01 | 56.31 | -55.0959
0.955879 | 100.001 | 9.55865e-3 | 2790.00 | 56.53 | -54.5220
0.949272 | 99.9995 | 9.49277e-3 | 2800.01 | 56.64 | -54.9763
0.944813 | 99.9932 | 9.44878e-3 | 2810.02 | 56.81 | -61.0004
0.937335 | 100.003 | 9.37305e-3 | 2820.00 | 57.03 | -57.2210
0.937419 | 99.9986 | 9.37432e-3 | 2830.01 | 57.14 | -55.8473
0.924217 | 99.9983 | 9.24232e-3 | 2840.01 | 57.33 | -52.6965
0.927338 | 99.9960 | 9.27375e-3 | 2850.01 | 57.51 | -55.4749
0.915217 | 100.003 | 9.15185e-3 | 2860.01 | 57.64 | -56.7254
0.912746 | 100.003 | 9.12717e-3 | 2870.00 | 57.84 | -55.0810
0.899633 | 100.001 | 8.99628e-3 | 2880.01 | 58.00 | -58.8025
0.899371 | 99.9998 | 8.99373e-3 | 2890.00 | 58.16 | -56.5947
0.891116 | 99.9983 | 8.91131e-3 | 2900.00 | 58.32 | -55.2866
0.886258 | 100.001 | 8.86248e-3 | 2910.01 | 58.48 | -55.8464
0.888174 | 100.003 | 8.88143e-3 | 2920.00 | 58.66 | -58.0764
0.876763 | 99.9980 | 8.76780e-3 | 2930.00 | 58.82 | -59.5972
0.878494 | 100.000 | 8.78491e-3 | 2940.00 | 59.01 | -54.7912
0.865942 | 99.9986 | 8.65954e-3 | 2950.00 | 59.20 | -57.9236
0.872662 | 99.9972 | 8.72687e-3 | 2960.00 | 59.35 | -62.9025
0.856811 | 100.004 | 8.56773e-3 | 2970.01 | 59.45 | -58.2203
0.853952 | 100.005 | 8.53912e-3 | 2980.01 | 59.64 | -61.8584
0.842976 | 100.000 | 8.42976e-3 | 2990.01 | 59.82 | -57.1140
0.843066 | 99.9995 | 8.43070e-3 | 3000.00 | 60.02 | -60.2249

**Comment by ManonMarchand** [comment]
Hi Marco!

The data I was showing comes from the wolfram alpha chemical database. When plotted together with your data it looks like this : 

![image](https://user-images.githubusercontent.com/16650466/162158906-22d6cdde-a792-4aec-a496-40f65a76cb87.png)

Do you think we should rather use your experiment? I agree that it looks better but the viscosity you measure is a bit lower than what can be found in the tables. 
Maybe there was a bit of water in the sample cause propylene glycol is hygroscopic?  It will also be the case in situ for the samples.

**Comment by ManonMarchand** [comment]
Actualization : I made a small literature exploration : 

![image](https://user-images.githubusercontent.com/16650466/162169446-433ee184-db74-4519-a214-fdf8291c80ee.png)

Your data is in good agreement with other experiments. I'll take it and update the figures soon :)

**Comment by marcocaggioni** [comment]
Thanks for checking!
closing the issue!
